#version: '3.8'
services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile_elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  kibana:
    build:
      context: .
      dockerfile: Dockerfile_kibana
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  logstash:
    build:   
      context: .
      dockerfile: Dockerfile_logstash
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./data:/usr/share/logstash/data  

volumes:
  elastic_data:
    driver: local  
