FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.7

COPY config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml


RUN chown elasticsearch:elasticsearch /usr/share/elasticsearch/config/elasticsearch.yml

EXPOSE 9200 9300

CMD ["elasticsearch"]
