#version: '3.8'
services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile_elasticsearch
    container_name: elasticsearch_stream
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  kibana:
    build:
      context: .
      dockerfile: Dockerfile_kibana
    container_name: kibana-stream
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  logstash:
    build:   
      context: .
      dockerfile: Dockerfile_logstash
    container_name: logstash_stream
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./data:/usr/share/logstash/data

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.17.0
    container_name: metricbeat_stream
    user: root
    volumes:
      - ./config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
  
    depends_on:
      - elasticsearch
      - logstash
      - kibana
    command: ["/bin/sh", "-c", "chmod go-w /usr/share/metricbeat/metricbeat.yml && metricbeat -e -c /usr/share/metricbeat/metricbeat.yml"]

volumes:
  elastic_data:
    driver: local  
