metricbeat.modules:
  - module: elasticsearch
    metricsets: ["node", "node_stats", "cluster_stats"]
    period: 10s
    hosts: ["http://elasticsearch:9200"]

  - module: logstash
    metricsets: ["node", "node_stats"]
    period: 10s
    hosts: ["http://logstash_stream:9600"]

  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana-stream:5601"
